raft_model: raft-sintel

use_3d: False

# device/batch size for raft & geometric optical flow
device: cuda
batch_size: 18

original_fps: 15
# run once every `skip_frames` frames
skip_frames: 2

output: 'out/highbay_test_5'

raft:
  path: ${RAFT}/core/
  model: ${RAFT}/models/${RAFT_MODEL}.pth
  iters: 12

time:
  relative: true
  t0: 120
  tf: 130
  # t0: 915
  # tf: 930
  # t0: 20
  # t0: 715
  # tf: 750

img_data:
  path: "~/Downloads/cv_bag2"
  topic: /camera/camera/color/image_raw
  camera_info_topic: /camera/camera/color/camera_info
  compressed: False
  
depth_data:
  path: "~/Downloads/cv_bag2"
  topic: /camera/camera/depth/image_rect_raw
  camera_info_topic: /camera/camera/depth/camera_info
  compressed: False

  depth_scale: 1000.0
  max_depth: 10.0

  # d, sigmalColor, sigmalSpace. Delete or set to null to disable.
  # bilateral_smooth_depth: [5, 35, 5] # in mm. (before scaling by 1000.0)

pose_data:
  type: bag
  path: "~/Downloads/odometry"
  topic: /BD01/world
  time_tol: 5.0

tracking:
  # for 3D:
  # if residual magnitude is greater than (min_vel_threshold + depth * vel_threshold_gain) * 1 / fps, 
  # then that point is considered dynamic
  # for 2D:
  # approximate 3d residual magnitude = depth * K^-1 * [delta_u, delta_v, 0]
  min_vel_threshold: 0.5
  vel_threshold_gain: 0.1

  gaussian_smoothing: False
  gaussian_kernel_size: 7

  post_processing: []
  # post_processing: [['open', 3], ['close', 3]]

  # maximum chamfer distance for a projected dynamic object & a newly detected
  # dynamic object to be considered for GNN association
  max_chamfer_distance: 0.25

viz:
  viz_video: True
  viz_dynamic_object_masks: True
  vid_dims: [1024, 656]
  viz_flag_names: ['image', 'depth', 'dynamic mask', 'raft flow', 'residual', 'orig_dynamic_mask']
  # must be 2D: each entry i means viz_flag_names[i] will be in the video at the location of i in the grid
  viz_flags: [[0, 1, 2], [3, 4, 5]]
  viz_max_residual_magnitude: 2.0