# KMD demo configuration file
# required environment variables:
#   KMD: path to the KMD directory
#   ROBOT: name of the robot (e.g. 'thoth')
#   RAFT: path to root of RAFT repository
#   RAFT_MODEL: name of the RAFT model (e.g. 'raft-sintel')

# device/batch size for geometric optical flow
device: cuda
batch_size: 24

original_fps: 30
# run once every `skip_frames` frames
skip_frames: 5

output: 'optical_flow_diff_skip_2'

raft:
  path: ${RAFT}/core/
  model: ${RAFT}/models/${RAFT_MODEL}.pth
  iters: 12
  device: cuda
  batch_size: 36

time:
  relative: true
  t0: 695
  tf: 750

img_data:
  path: "${KMD}/bags/${ROBOT}.bag"
  topic: /${ROBOT}/forward/color/image_raw/compressed
  camera_info_topic: /${ROBOT}/forward/color/camera_info
  compressed: True
  
depth_data:
  path: "${KMD}/bags/${ROBOT}.bag"
  topic: /${ROBOT}/forward/depth/image_rect_raw
  camera_info_topic: /${ROBOT}/forward/depth/camera_info
  compressed: False
  depth_scale: 1000.0
  max_depth: 10.0

pose_data:
  type: bag
  path: ${KMD}/kimera_vio/${ROBOT}.bag
  topic: /${ROBOT}/kimera_vio_ros/odometry
  time_tol: 0.5