# KMD demo configuration file
# required environment variables:
#   KMD: path to the KMD directory root (parent directory of /hybrid, /outdoor, etc.)
#   RAFT: path to root of RAFT repository
#   RAFT_MODEL: name of the RAFT model (e.g. 'raft-sintel')

# optional environment variables:
#   KMD_ENV: KMD environment (e.g. 'hybrid', 'outdoor')
#   ROBOT: name of the robot (e.g. 'thoth')
#   RAFT_MODEL: name of the RAFT model (e.g. 'raft-sintel')
# will be overriden by this config file if the following are set:
# kmd_env: outdoor
# robot: thoth
kmd_env: hybrid
robot: sparkal1
raft_model: raft-sintel

use_3d: False

# device/batch size for raft & geometric optical flow
device: cuda
batch_size: 24

original_fps: 30
# run once every `skip_frames` frames
skip_frames: 5

# output: 'out/outdoor_thoth_skip_2'
output: 'out/contours_hybrid_sparkal1_max_15'

raft:
  path: ${RAFT}/core/
  model: ${RAFT}/models/${RAFT_MODEL}.pth
  iters: 12

time:
  relative: true
  # t0: 40
  # tf: 80
  # t0: 915
  # tf: 930
  t0: 695
  # t0: 715
  tf: 750

img_data:
  path: "${KMD}/${KMD_ENV}/bags/${ROBOT}.bag"
  topic: /${ROBOT}/forward/color/image_raw/compressed
  camera_info_topic: /${ROBOT}/forward/color/camera_info
  compressed: True
  
depth_data:
  path: "${KMD}/${KMD_ENV}/bags/${ROBOT}.bag"
  topic: /${ROBOT}/forward/depth/image_rect_raw
  camera_info_topic: /${ROBOT}/forward/depth/camera_info
  compressed: False

  depth_scale: 1000.0
  max_depth: 15.0

  # d, sigmalColor, sigmalSpace. Delete or set to null to disable.
  bilateral_smooth_depth: [5, 35, 5] # in mm. (before scaling by 1000.0)

pose_data:
  type: bag
  path: ${KMD}/${KMD_ENV}/kimera_vio/${ROBOT}.bag
  topic: /${ROBOT}/kimera_vio_ros/odometry
  time_tol: 5.0

tracking:
  # for 3D:
  # if residual magnitude is greater than (min_vel_threshold + depth * vel_threshold_gain) * 1 / fps, 
  # then that point is considered dynamic

  # for 2D:
  # approximate 3d residual magnitude = depth * K^-1 * [delta_u, delta_v, 0]

  min_vel_threshold: 1.5
  vel_threshold_gain: 0.2

  gaussian_smoothing: False
  gaussian_kernel_size: 7

  post_processing: [['open', 9], ['close', 13]]

viz:
  viz_video: True
  viz_dynamic_object_masks: True
  vid_dims: [1024, 768]
  viz_flag_names: ['image', 'depth', 'dynamic mask', 'raft flow', 'residual', 'orig_dynamic_mask']
  # must be 2D: each entry i means viz_flag_names[i] will be in the video at the location of i in the grid
  viz_flags: [[0, 1, 2], [3, 4, 5]]
  viz_max_residual_magnitude: 2.0